apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "softwareag-commandcentral.fullname" . }}
  labels:
    app: {{ template "softwareag-commandcentral.name" . }}
    chart: {{ template "softwareag-commandcentral.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "softwareag-commandcentral.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "softwareag-commandcentral.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: {{ default 0 .Values.RunAsUser }}
{{- if and (.Values.RunAsUser) (.Values.FsGroup) }}
{{- if not (eq .Values.RunAsUser 0.0) }}
        fsGroup: {{ .Values.FsGroup }}
{{- end }}
{{- end }}
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: https
            containerPort: 8091
            protocol: TCP
          - name: repo
            containerPort: 8090
            protocol: TCP
        volumeMounts:
          - name: commandcentral-data
            mountPath: /opt/sagtools/profiles/CCE/data/
          - name: commandcentral-provisioning
            mountPath: /opt/sagtools/profiles/SPM/configuration/provisioning
        livenessProbe:
          initialDelaySeconds: 600
          periodSeconds: 30
          httpGet:
            path: '/cce/web/#'
            port: 8091
            scheme: HTTPS
        resources:
{{ toYaml .Values.resources | indent 12 }}
        readinessProbe:
          initialDelaySeconds: 600
          periodSeconds: 30
          httpGet:
            path: '/cce/web/#'
            port: 8091
            scheme: HTTPS
      volumes:
      - name: commandcentral-data
     {{- if .Values.Persistence.Enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.Persistence.ExistingDataClaim | default (include "softwareag-commandcentral.fullname" .) }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: commandcentral-provisioning
     {{- if .Values.Persistence.Enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.Persistence.ExistingProvisioningClaim | default (include "softwareag-commandcentral.fullname" .) }}-provisioning
      {{- else }}
        emptyDir: {}
      {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}

