apiVersion: v1
kind: Service
metadata:
  name: {{ template "softwareag-commandcentral.fullname" . }}
  labels:
    app: {{ template "softwareag-commandcentral.name" . }}
    chart: {{ template "softwareag-commandcentral.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
    - port: {{ .Values.service.repoPort }}
      targetPort: {{ .Values.service.repoPort }}
      protocol: TCP
      name: cc-repo
  selector:
    app: {{ template "softwareag-commandcentral.name" . }}
    release: {{ .Release.Name }}
